CREATE DATABASE NexusSupport;
GO

USE NexusSupport;
GO

CREATE TABLE Departments (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Employees (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Role NVARCHAR(100) NOT NULL,
    DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
    StartDate DATE NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE Customers (
    Id INT PRIMARY KEY IDENTITY(1,1),
    CompanyName NVARCHAR(100) NOT NULL,
    ContactName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    ContractTier NVARCHAR(20) NOT NULL,
    ContractValue DECIMAL(10,2) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE Tickets (
    Id INT PRIMARY KEY IDENTITY(1,1),
    CustomerId INT FOREIGN KEY REFERENCES Customers(Id),
    AssignedEmployeeId INT FOREIGN KEY REFERENCES Employees(Id),
    Title NVARCHAR(200) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    Priority NVARCHAR(20) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    CreatedDate DATETIME NOT NULL,
    ResolvedDate DATETIME NULL
);
